Repository adfinis-sygroup/ansible-roles, pull requests merged in 2018-03, with the labels that each got.

#53 hwraid: fix ansible condition if there is no ansible_devices.sda
  hwraid/tasks/installation.yml
Labels: bug, easy

#54 console: create a new vimrc global configuration file
  console/templates/etc/vimrc.j2
Labels: bug, easy

#51 grub: add optional additional cmdline parameters
  grub/defaults/main.yml
  grub/templates/etc/default/grub.j2
Labels: easy, enhancement

#49 Network templates
  network/defaults/main.yml
  network/templates/etc/Debian/ethernet.j2
  network/templates/etc/RedHat/bond.j2
  network/templates/etc/RedHat/bridge.j2
  network/templates/etc/RedHat/ethernet.j2
  network/templates/etc/RedHat/header.j2
  network/templates/etc/RedHat/ipv4.j2
  network/templates/etc/RedHat/ipv6.j2
Labels: enhancement

#56 console: install bash-completion on RedHat based systems
  console/vars/RedHat.yml
Labels: easy, enhancement

#58 network: don't set sysctl rules for vnet* devices, they change to often
  network/templates/etc/sysctl.d/network_ipv6_ra.conf.j2
Labels: enhancement

#57 console: install htop on RedHat based systems
  console/vars/RedHat.yml
Labels: easy, enhancement

#59 role docker
  docker/defaults/main.yml
  docker/handlers/main.yml
  docker/meta/main.yml
  docker/tasks/configuration.yml
  docker/tasks/installation.yml
  docker/tasks/main.yml
  docker/templates/etc/docker/daemon.json.j2
  docker/vars/Debian.yml
  docker/vars/RedHat.yml
Labels: enhancement, role

#60 Rename CentOS platform to EL in metadata
  _template/meta/main.yml
  ansible/meta/main.yml
  console/meta/main.yml
  docker/meta/main.yml
  grub/meta/main.yml
  hostname/meta/main.yml
  hw_vm_tools/meta/main.yml
  hwraid/meta/main.yml
  ipmi/meta/main.yml
  iptables/meta/main.yml
  mariadb/meta/main.yml
  motd/meta/main.yml
  network/meta/main.yml
  nginx/meta/main.yml
  nodejs/meta/main.yml
  ntp/meta/main.yml
  pkg_mirror/meta/main.yml
  pki/meta/main.yml
  postfix/meta/main.yml
  rpcbind/meta/main.yml
  rsyslog/meta/main.yml
  snmp/meta/main.yml
  ssh/meta/main.yml
  telegraf/meta/main.yml
  upgrade/meta/main.yml
  users/meta/main.yml
Labels: bug, easy
